// actionTypes.js
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const MARK_COMPLETED = 'MARK_COMPLETED';
export const MARK_INCOMPLETE = 'MARK_INCOMPLETE';
export const FILTER_TODOS = 'FILTER_TODOS';
export const MARK_ALL_COMPLETED = 'MARK_ALL_COMPLETED';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';